/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export enum UserRole {
  ADMIN = "Administrator",
  ASSET_MANAGER = "Asset Manager",
  DEPT_MANAGER = "Department Manager",
  AUDITOR = "Auditor",
  EMPLOYEE = "Employee"
}

export enum AssetStatus {
  ACTIVE = "Active",
  UNDER_MAINTENANCE = "Under Maintenance",
  DAMAGED = "Damaged",
  LOST = "Lost",
  DISPOSED = "Disposed"
}

export enum AssetCondition {
  EXCELLENT = "Excellent",
  GOOD = "Good",
  FAIR = "Fair",
  POOR = "Poor"
}

export enum TransferStatus {
  PENDING = "Pending Approval",
  APPROVED = "Approved",
  REJECTED = "Rejected"
}

export enum VerificationResult {
  VERIFIED = "Verified",
  MISSING = "Missing",
  DAMAGED = "Damaged"
}

export type MalawiRegion = "Northern Region" | "Central Region" | "Southern Region";

export type MalawiClientType =
  | "Government Ministry"
  | "Government Department"
  | "District Council"
  | "NGO"
  | "International Organization"
  | "School"
  | "College / University"
  | "Hospital / Health Facility"
  | "Bank"
  | "Private Company"
  | "Small Business"
  | "Individual Client";

export const MALAWI_REGIONS: MalawiRegion[] = ["Northern Region", "Central Region", "Southern Region"];

export const MALAWI_DISTRICTS: Record<MalawiRegion, string[]> = {
  "Northern Region": ["Chitipa", "Karonga", "Rumphi", "Mzimba", "Nkhata Bay", "Likoma"],
  "Central Region": ["Kasungu", "Mchinji", "Dowa", "Ntchisi", "Salima", "Nkhotakota", "Lilongwe", "Dedza", "Ntcheu"],
  "Southern Region": ["Mangochi", "Balaka", "Machinga", "Zomba", "Chiradzulu", "Blantyre", "Mwanza", "Neno", "Thyolo", "Mulanje", "Phalombe", "Chikwawa", "Nsanje"]
};

export const MALAWI_CLIENT_TYPES: MalawiClientType[] = [
  "Government Ministry",
  "Government Department",
  "District Council",
  "NGO",
  "International Organization",
  "School",
  "College / University",
  "Hospital / Health Facility",
  "Bank",
  "Private Company",
  "Small Business",
  "Individual Client"
];

export interface UserPreferences {
  theme: "light" | "dark" | "system";
  accentColor: "blue" | "emerald" | "rose" | "violet" | "amber" | "indigo";
  layout: "grid" | "compact" | "wide";
  sidebarStyle: "dark" | "light" | "compact";
  fontSize: "sm" | "md" | "lg";
  emailNotif: boolean;
  desktopNotif: boolean;
  assignmentNotif: boolean;
}

export interface User {
  id: string;
  name: string;
  email: string;
  role: UserRole;
  departmentId: string;
  clientId?: string;
  forcePasswordChange: boolean;
  createdAt: string;
  lastLogin?: string;
  phone?: string;
  bio?: string;
  avatar?: string;
  totpEnabled?: boolean;
  totpSecret?: string;
  loginHistory?: Array<{timestamp: string; event: string; device: string; browser: string; ip: string; status: "success" | "failed"}>;
  activeSessions?: Array<{id: string; loginTime: string; device: string; browser: string; ip: string}>;
  preferences?: UserPreferences;
}

export interface Category {
  id: string;
  name: string;
  code: string;
  serviceIntervalDays?: number; // Predefined recurring maintenance service interval in days
}

export interface Department {
  id: string;
  name: string;
  code: string;
}

export interface Client {
  id: string;
  name: string;
  code: string;
  contactPerson: string;
  phone: string;
  email: string;
  address: string;
  organizationType: string;
  district?: string;
  region?: MalawiRegion;
  postalAddress?: string;
  registrationNumber?: string;
  tinNumber?: string;
  registrationDate: string;
  status: "Active" | "Inactive";
  departmentId?: string;
}

export interface Location {
  id: string;
  name: string;
  code: string;
}

export interface Supplier {
  id: string;
  name: string;
  contactPerson: string;
  email: string;
  phone: string;
  address: string;
}

export interface Asset {
  id: string;
  assetTag: string; // Dynamic or custom, e.g. GPL-AST-0001
  name: string;
  clientId?: string; // Links asset custody to a client/customer/organization
  categoryId: string;
  departmentId: string;
  locationId: string;
  supplierId: string;
  purchaseDate: string;
  purchaseCost: number;
  serialNumber: string;
  warrantyExpiry: string;
  condition: AssetCondition;
  status: AssetStatus;
  assignedUserId?: string; // Links to User.id
  notes: string;
  image?: string;
  qrCode: string; // Autogenerated DataURL or representation
}

export interface AssetAssignment {
  id: string;
  assetId: string;
  userId: string;
  departmentId: string;
  assignedDate: string;
  returnDate?: string;
  status: "Active" | "Returned";
  remarks?: string;
}

export interface AssetTransfer {
  id: string;
  assetId: string;
  sourceDepartmentId: string;
  destDepartmentId: string;
  sourceLocationId: string;
  destLocationId: string;
  status: TransferStatus;
  transferDate: string;
  authorizedBy?: string; // User.name or User.id
  remarks?: string;
}

export interface MaintenanceRecord {
  id: string;
  assetId: string;
  requestBy: string; // User.name
  technician: string;
  serviceProvider: string;
  cost: number;
  maintenanceDate: string;
  completionDate?: string;
  notes: string;
  status: "Pending" | "In Progress" | "Completed" | "Cancelled";
}

export interface VerificationRecord {
  id: string;
  assetId: string;
  verificationDate: string;
  verifiedBy: string; // User.name
  status: AssetStatus;
  condition: AssetCondition;
  result: VerificationResult;
  notes: string;
}

export interface DisposalRecord {
  id: string;
  assetId: string;
  disposalDate: string;
  method: string; // e.g., Sold, Scrapped, Donated, Recycled
  reason: string;
  authorizedBy: string; // User.name
  supportingDocuments?: string; // Optional notes or supporting document references
}

export interface AuditLog {
  id: string;
  userId: string;
  userName: string;
  action: string;
  details: string;
  timestamp: string;
  ipAddress: string;
}

export type ReminderCategory =
  | "Office Rent"
  | "Internet"
  | "Electricity"
  | "Water"
  | "Domain"
  | "Hosting"
  | "Software Subscription"
  | "Maintenance"
  | "Verification"
  | "Insurance"
  | "Supplier Payment"
  | "Department Expense"
  | "Compliance Deadline"
  | "Custom Reminder"
  | "Internet Bundle Renewals"
  | "Office Rent Payments"
  | "Electricity Bills"
  | "Water Bills"
  | "Domain Renewals"
  | "Hosting Renewals"
  | "Software License Renewals"
  | "Vehicle Insurance"
  | "Equipment Maintenance"
  | "Asset Verification"
  | "Contract Renewals"
  | "Supplier Payments"
  | "Tax Deadlines"
  | "Staff Meetings"
  | "Custom Tasks";

export type ReminderRecurrence = "None" | "Daily" | "Weekly" | "Monthly" | "Quarterly" | "Semi-Annual" | "Annual";
export type ReminderPriority = "Low" | "Medium" | "High" | "Critical";

export type ReminderStatus = "Active" | "Completed" | "Snoozed" | "Cancelled";

export interface Reminder {
  id: string;
  title: string;
  description?: string;
  category: ReminderCategory;
  dueDate: string;
  recurrence: ReminderRecurrence;
  assignedTo: string;
  status: ReminderStatus;
  priority: ReminderPriority;
  clientId?: string;
  departmentId?: string;
  responsibleRole?: UserRole;
  responsibleUserId?: string;
  notificationSchedule?: number[];
  amount?: number;
  notes?: string;
  templateId?: string;
  createdBy?: string;
  createdByName?: string;
  createdAt: string;
  updatedAt: string;
  completedAt?: string;
  snoozedUntil?: string;
  completionNotes?: string;
  parentReminderId?: string;
  nextOccurrenceGenerated?: boolean;
}

export interface ReminderTemplate {
  id: string;
  name: string;
  description?: string;
  category: ReminderCategory;
  defaultPriority: ReminderPriority;
  defaultRecurrence: ReminderRecurrence;
  defaultNotificationSchedule: number[];
  defaultDepartmentId?: string;
  defaultClientId?: string;
  defaultResponsibleRole?: UserRole;
  defaultResponsibleUserId?: string;
  titleTemplate: string;
  descriptionTemplate: string;
  notesTemplate?: string;
  archived: boolean;
  createdBy: string;
  createdByName: string;
  modifiedBy: string;
  modifiedByName: string;
  createdAt: string;
  updatedAt: string;
  tags: string[];
}

export interface Notification {
  id: string;
  userId: string; // "all" or specific User.id
  reminderId?: string;
  title: string;
  message: string;
  isRead: boolean;
  createdAt: string;
  sentAt?: string;
  readAt?: string;
  status?: "pending" | "sent" | "failed";
  channel?: "in-app" | "dashboard" | "email" | "push" | "sms";
  deliveryKey?: string;
  type: "info" | "warning" | "success" | "error";
}

export interface NotificationPreference {
  userId: string;
  emailEnabled: boolean;
  pushEnabled: boolean;
  smsEnabled: boolean;
}

export type DocumentScope = "global" | "department" | "personal" | "asset" | "client";
export type DocumentApprovalStatus = "Draft" | "Pending Approval" | "Approved" | "Archived";
export type DocumentExportFormat = "PDF" | "Excel" | "Word" | "CSV" | "Print";

export interface DocumentSignature {
  id: string;
  signerId?: string;
  signerName: string;
  signerRole?: string;
  signedAt: string;
  signatureData?: string;
  purpose?: string;
}

export interface DocumentTemplate {
  id: string;
  name: string;
  docType: string;
  description: string;
  htmlTemplate: string;
  version: number;
  archived: boolean;
  createdBy: string;
  createdByName: string;
  modifiedBy: string;
  modifiedByName: string;
  createdAt: string;
  updatedAt: string;
  tags: string[];
}

export interface DocumentRecord {
  id: string;
  docType: string;
  title: string;
  description: string;
  htmlContent: string;
  plainText: string;
  scope: DocumentScope;
  sourceType: string;
  sourceId: string;
  sourceFingerprint: string;
  version: number;
  approvalStatus: DocumentApprovalStatus;
  createdBy: string;
  createdByName: string;
  modifiedBy: string;
  modifiedByName: string;
  createdAt: string;
  updatedAt: string;
  archivedAt?: string;
  archived: boolean;
  isAutoGenerated: boolean;
  receiptNumber?: string;
  amount?: number;
  currency?: string;
  paymentMethod?: string;
  clientId?: string;
  assetId?: string;
  departmentId?: string;
  tags: string[];
  attachments: string[];
  signatures: DocumentSignature[];
  printCount: number;
  lastPrintedAt?: string;
  qrPayload?: string;
}

export interface DocumentPrintHistory {
  id: string;
  documentId: string;
  documentTitle: string;
  documentType: string;
  exportedFormat: DocumentExportFormat;
  printedBy: string;
  printedByName: string;
  printedAt: string;
  organization: string;
}

export interface SystemSettings {
  orgName: string;
  logo: string; // Data URL or text-based logo abbreviation
  theme: "light" | "dark";
  emailHost: string;
  emailPort: string;
  emailSender: string;
  isNotificationsEnabled: boolean;
  backupFrequency: "daily" | "weekly" | "monthly" | "manual";
  orgAddress?: string;
  orgPhone?: string;
  orgEmail?: string;
  orgWebsite?: string;
  orgFooterText?: string;
  orgDefaultLanguage?: string;
  systemTheme?: "light" | "dark" | "system";
  currency?: string;
  timezone?: string;
  dateFormat?: string;
  country?: string;
  phoneFormat?: string;
  reminderIntervals?: number[];
  companySlogan?: string;
  companyDescription?: string;
  socialLinks?: {
    website?: string;
    linkedin?: string;
    facebook?: string;
    x?: string;
  };
  officeLocations?: Array<{
    id: string;
    name: string;
    address: string;
    phone: string;
    email: string;
  }>;
  businessRegistration?: string;
  primaryColor?: string;
  secondaryColor?: string;
  layoutDensity?: "comfortable" | "compact";
  typography?: string;
  homeContent?: string;
  aboutContent?: string;
  services?: string[];
  teamMembers?: Array<{ id: string; name: string; role: string; email: string; phone?: string }>;
  announcements?: Array<{ id: string; title: string; body: string; date: string }>;
}
